---
dist: xenial
language: python
python:
  - "3.7"
cache:
  directories:
    - '$HOME/.sonar/cache'
install:
  - pip install -r requirements.txt
  - pip install codecov
addons:
  sonarcloud:
    organization: "attilabogar-github"
script:
  - sonar-scanner
  - coverage run tests.py
after_success:
  - codecov
